# This is a basic workflow to help you get started with Actions
 
 name: 020-manual-input-workflow
 
 # Controls when the workflow will run
 on:
   # Triggers the workflow on push or pull request events but only for the "main" branch
   workflow_dispatch:
     # Inputs the workflow accepts.
     inputs:
       #Friendly description to be shown in the UI instead of 'name'
       default: 'World DP'
       #Input has to be provided for the workflow to rub
       required: true
       
 
 
 # A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
   # This workflow contains a single job called "greet"
   greet:
     # The type of runner that the job will run on
     runs-on: ubuntu-latest
 
     # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
 
       # Runs a single command using the runners shell
       - name: Send greeting
         run: echo "Hello, $${{ github.event.inputs.name }}"
