# This is a basic first workflow to help get started with Actions
name: My First GitHub Action

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-release:
   runs-on: ubuntu-latest
   
  echo-job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: First echo
        run: echo "Hello from my first GitHub Action!"

      - name: Second multi line echo
        run: |
           echo "This is the first line running on the runner."
           echo "This is the second line running on the runner."
           
